BEGIN;

CREATE TYPE device_type AS ENUM (
    'Android',
    'iPhone',
    'Windows',
    'Macbook'
);

CREATE TYPE device_condition AS ENUM (
    'very good',
    'good',
    'okay',
    'damaged'
);

CREATE TYPE device_location AS ENUM (
    'Albany, NY',
    'Schenectady, NY'
);

CREATE TABLE reconnect_posts (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    title TEXT NOT NULL,
    description TEXT NOT NULL,
    device device_type NOT NULL,
    condition device_condition NOT NULL,
    location device_location NOT NULL,
    date_created TIMESTAMPTZ NOT NULL DEFAULT now(),
    user_id INTEGER REFERENCES reconnect_users(id) ON DELETE CASCADE NOT NULL
);

COMMIT;