BEGIN;

CREATE TABLE reconnect_messages_threads (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    author_id INTEGER REFERENCES reconnect_users(id) NOT NULL,
    recipient_id INTEGER REFERENCES reconnect_users(id) NOT NULL,
    date_created TIMESTAMPTZ DEFAULT now() NOT NULL
);

CREATE TABLE reconnect_messages (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    content TEXT NOT NULL,
    thread_id INTEGER REFERENCES reconnect_messages_threads(id) NOT NULL,
    author_id INTEGER REFERENCES reconnect_users(id) NOT NULL,
    date_created TIMESTAMPTZ DEFAULT now() NOT NULL
);

COMMIT;